import type { University } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const universities: University[] = [
  {
    id: '1',
    name: 'Massachusetts Institute of Technology (MIT)',
    country: 'USA',
    costLevel: 'High',
    acceptanceChance: 'Low',
    fit: 'Excellent fit for your interest in Computer Science and strong academic profile.',
    risks: 'Extremely competitive admissions process and high tuition fees.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-1')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-1')?.imageHint || '',
    fields: ['Computer Science', 'Engineering', 'Physics', 'Mathematics'],
  },
  {
    id: '2',
    name: 'Stanford University',
    country: 'USA',
    costLevel: 'High',
    acceptanceChance: 'Low',
    fit: 'Top-ranked for innovation and technology, aligns with your ambitious goals.',
    risks: 'Very low acceptance rate and high cost of living in the area.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-2')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-2')?.imageHint || '',
    fields: ['Innovation', 'Technology', 'Business', 'Law'],
  },
  {
    id: '3',
    name: 'University of Toronto',
    country: 'Canada',
    costLevel: 'Medium',
    acceptanceChance: 'Medium',
    fit: 'A strong program in your field of study and a more affordable option.',
    risks: 'Large class sizes and competitive environment for co-op placements.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-3')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-3')?.imageHint || '',
    fields: ['AI', 'Data Science', 'Medicine', 'Robotics'],
  },
  {
    id: '4',
    name: 'University of Waterloo',
    country: 'Canada',
    costLevel: 'Medium',
    acceptanceChance: 'Medium',
    fit: 'Renowned for its co-op program, offering excellent work experience.',
    risks: 'Highly focused on tech, might be less diverse in other fields.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-4')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-4')?.imageHint || '',
    fields: ['Tech', 'Co-op', 'Engineering', 'Quantum Computing'],
  },
  {
    id: '5',
    name: 'Arizona State University',
    country: 'USA',
    costLevel: 'Medium',
    acceptanceChance: 'High',
    fit: 'Good program with a high acceptance rate, making it a solid safe option.',
    risks: 'May not have the same prestige as top-tier universities.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-5')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-5')?.imageHint || '',
    fields: ['Engineering', 'Business', 'Arts', 'Sustainability'],
  },
  {
    id: '6',
    name: 'Dalhousie University',
    country: 'Canada',
    costLevel: 'Low',
    acceptanceChance: 'High',
    fit: 'Affordable tuition and a good computer science program, located in a vibrant city.',
    risks: 'Less internationally recognized compared to larger Canadian universities.',
    imageUrl: PlaceHolderImages.find(img => img.id === 'university-6')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(img => img.id === 'university-6')?.imageHint || '',
    fields: ['Computer Science', 'Marine Biology', 'Health', 'Oceanography'],
  },
];
